dist: xenial
language: python
cache: pip
sudo: required
services:
- docker

before_script:
- docker build -t builder .

script:
- docker run --rm -v $PWD/dist:/dist builder

# Travis encryption where GITHUB_OAUTH_TOKEN is
# a GitHub token with public_repo access
# ---------------------------------------------
# docker run -it --rm ruby bash
# gem install travis
# travis encrypt -r ome/zeroc-ice-py-ubuntu1404 $GITHUB_OAUTH_TOKEN
# In travis-ci, add a new env var, 
# key GITHUB_OAUTH_TOKEN value: the value generated
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/zeroc*
  skip_cleanup: true
  on:
    tags: true
